### ISSUE TITLE
Android Spashscreen

### ISSUE THREAD

**Issue by benpaddlejones** [HalfbeardStudios/Student-Voice#2]
We need splash screens that load instantly while the app is loading (rather than user staring at blank screen. Landscape & Portrait images are needed in the following size:
xlarge 960dp x 720dp
large 640dp x 480dp
normal 470dp x 320dp
small 426dp x 320dp

Read more here:
http://cordova.apache.org/docs/en/edge/config_ref_images.md.html#Icons%20and%20Splash%20Screens_
http://developer.android.com/guide/practices/screens_support.html

**Comment by gypodra** [comment]
I'll look into it and I'll ask Vincent if he can make something.

**Comment by benpaddlejones** [comment]
Vincent was assigned the issue already, you need to focus on delivering the search for a school functionality. ;-)

**Comment by gypodra** [comment]
Fark. Ok I'll get as much CSS done today and start researching that.
-Ali Hamieh

**Comment by VPBergo** [comment]
I'll try and drop by Arian's place to work on the graphics tomorrow.

**Comment by benpaddlejones** [comment]
Cool, checkout the config.xml for the filenames and locations

**Comment by VPBergo** [comment]
I added all the splashscreen images. Please place them in the config file. :dancer:

**Comment by benpaddlejones** [comment]
Open the config.xml file in notepad++ and you see the naming conventions/locations then rerun build phonegap, download and install the apk and you should see your work

**Comment by benpaddlejones** [comment]
Files need to be named like this (note no special characters or spaces in filename):

<gap:splash src="images/splashscenelandhdpi.png" gap:platform="android" gap:density="land-hdpi" />
<gap:splash src="images/splashscenelandldpi.png" gap:platform="android" gap:density="land-ldpi" />
<gap:splash src="images/splashscenelandmdpi.png" gap:platform="android" gap:density="land-mdpi" />
<gap:splash src="images/splashscenelandxhdpi.png" gap:platform="android" gap:density="land-xhdpi" />
<gap:splash src="images/splashsceneporthdpi.png" gap:platform="android" gap:density="port-hdpi" />
<gap:splash src="images/splashsceneportldpi.png" gap:platform="android" gap:density="port-ldpi" />
<gap:splash src="images/splashsceneportmdpi.png" gap:platform="android" gap:density="port-mdpi" />
<gap:splash src="images/splashsceneportxhdpi.png" gap:platform="android" gap:density="port-xhdpi" />
<icon src="images/icon.png" />

**Comment by benpaddlejones** [comment]
http://developer.android.com/tools/help/draw9patch.html to remove need for landscape and portrate splashscreens

**Comment by gypodra** [comment]
Fixed by Jones.
