### ISSUE TITLE
TypeError: 0 is not a function. Search-Script

### ISSUE THREAD

**Issue by ajahiri** [HalfbeardStudios/Student-Voice#20]
There is an error in the search script, this is halting the Javascript from running after that point. Seach function still works but the form-control script will not load because of this error.

Error on line 9 of file search-script.

Please pull the latest and debug.

**Comment by ajahiri** [comment]
@gypodra

**Comment by ajahiri** [comment]
*Update I tested the app when disabling the search-script completely and the problem still persists. Submit button and menu button don't seem to do anything. I'm going to look over the form-control code for errors, might be that.

**Comment by gypodra** [comment]
Are you still working in seperate folders?

**Comment by ajahiri** [comment]
Tried with code in one file and with code separated, same problem.

**Comment by ajahiri** [comment]
Tested code by running the email composer code after init for the sidebar and sidebar works, I assume there is a problem with the email composer plugin.

**Comment by gypodra** [comment]
If you still have the test code that Jones and I wrote, run it and see if
it picks up the name and its corresponding email. If it works then you
probably have problems with your plugin.

**Comment by ajahiri** [comment]
Problem is fixed, reverted to old code.
