### ISSUE TITLE
Search code, not allowing form-control code to function.

### ISSUE THREAD

**Issue by ajahiri** [HalfbeardStudios/Student-Voice#21]
After testing and debugging, the form-control code works properly but the emailSchoolEmail variable was showing up as undefined, when inputting the search code and form-control code into one file, it wont let the  sidebar or the event listeners load because of an error. There is an error in the search code even when the search function works.

**Comment by ajahiri** [comment]
@benpaddlejones

**Comment by ajahiri** [comment]
Error code when running in chrome. 

Uncaught TypeError: 0 is not a function on line 9 of main-script.js

The reason I know that this is creating a pause in the code is because there should be another error from the app because its running in chrome, since that error is not coming up I can conclude that there is a problem with the search-script.

**Comment by benpaddlejones** [comment]
Try putting the email array in it's own js file then calling it above all form div's sounds like it may be a heirachy issue, child called before parent. JS searches all and add to men but HTML runs vertically.

**Comment by gypodra** [comment]
What exactly isn't working in the form?

**Comment by benpaddlejones** [comment]
Form is "technically" working but us throwing an error (check JavaScript console). Could be what is causing lag or may cause future stability issue. Fixing is not an option... Read my last message for where to start!

**Comment by gypodra** [comment]
Making some progress. When adding the Testing code back in, everything seems to work normally.

**Comment by gypodra** [comment]
We have gotten it to work in a very weird way. When adding in the Testing (alertTest) function in the JS file, everything seems to work normally. We will keep de-bugging to figure out why, but for now we're deciding to keep that code in there just so we can continue working on the app.

**Comment by gypodra** [comment]
And we're keeping this Issue open until we actually fix it.

**Comment by benpaddlejones** [comment]
"We're keeping this issue open until we actually fix it" LMAO! No... let's close it while its still an issue and pretend it's no there... I'm so changing your password for this one...

**Comment by gypodra** [comment]
1) I hate you.
2) I haven't changed my password yet...

**Comment by ajahiri** [comment]
The TypeError only seems to happen when that is the first function called. I rearranged the code so that this doesn't happen. I have moved the form-control and sendEmail code to the top of the file and left some other event listeners at the bottom while leaving the search code in the middle. The code works fine and it is reading and injecting the school email properly.
