### ISSUE TITLE
Reduce Fonts Linked

### ISSUE THREAD

**Issue by ajahiri** [HalfbeardStudios/Student-Voice#8]
This is an issue we can resolve when we are doing optimizations but I'll leave it here so we don't forget. There are a lot of fonts that we don't use and we can delete them to save space and resource requirements.

**Comment by benpaddlejones** [comment]
As the app get closer to beta it will get more complex. You should cleanup as you go. If any fonts are defiantly not going to be needed clean them from the repo. Add to the name of unused a _unused tag so they are easy to identify. Add to that everyone should turn off notes and sync tracking in dreamweaver so their is no stray *.xml files.

**Comment by ajahiri** [comment]
No longer a problem, using Materialize and 1 font.
